### ISSUE TITLE
JCGS reviewer 1: (2) the "advice" is universal? 

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/lineup_residual_diagnostics#12]
Reviewer: "'The ubiquity of this advice is curious: investigating why, is the subject of this paper. ' I don't find this advice curious - it seems almost universal. I have taught this topic for many years and give the same advice. I explain why I give this advice and I believe several other authors do the same. Their reasons are wider in scope than you express in this article."

**Comment by TengMCing** [comment]
It is true that many statisticians agree with this advice. Perhaps we need to modify the introduction section.

**Comment by dicook** [comment]
We have replaced the "is curious" to better acknowledge that many practitioners already know this.

**Comment by TengMCing** [comment]
lack of empirical evidence for the advice is curious
